#!/usr/bin/python3
from block import Block
from chain import Chain
ch = Chain()
a = Block("A value")
b = Block("B value")
c = Block("C value")
ch.add_block(a)
ch.add_block(b)
ch.add_block(c)
print(ch.dict_chain())
