#!/usr/bin/python3
from block import Block
from chain import Chain
ch = Chain()
a = Block("1" ,"A value")
b = Block("2" ,"B value")
c = Block("3" ,"C value")
ch.add_block(a)
ch.add_block(b)
print(ch.dict_chain())
