#!/usr/bin/python3
from block import Block
from chain import Chain
from transaction import Transaction

ch = Chain()

first_transaction = Transaction("A top","B bottom","300")
a = Block(first_transaction.dict_transaction(), [])


second_transaction = Transaction("B top","C bottom","100")
b = Block(second_transaction.dict_transaction(), a.history)


third_transaction = Transaction("B top","A bottom","100")
c = Block(third_transaction.dict_transaction(), b.history)

ch.add_block(a)
ch.add_block(b)
ch.add_block(c)

print(ch.dict_chain())
